# Replace generate_emotion_voice in app.py with WORLD-CLASS version
import re

with open('app.py', 'r', encoding='utf-8') as f:
    content = f.read()

func_start = content.find('def generate_emotion_voice(')
rest = content[func_start+50:]
matches = list(re.finditer(r'(?<=\n)(?:def |class |# ={3,})', rest, re.MULTILINE))
func_end = func_start + 50 + matches[0].start()

new_func_lines = []
new_func_lines.append('def generate_emotion_voice(text, emotion="neutral", voice_type="male", output_path=None, elevenlabs_voice_id=None):')
new_func_lines.append('    """')
new_func_lines.append('    WORLD-CLASS EMOTION VOICE GENERATOR - 5-Tier Cascade')
new_func_lines.append('    Tier 1: ElevenLabs (Best Emotion Quality)')
new_func_lines.append('    Tier 2: Azure Cognitive Services (Premium Multilingual)')
new_func_lines.append('    Tier 3: Google Cloud TTS (Natural)')
new_func_lines.append('    Tier 4: Edge TTS (Free, Reliable)')
new_func_lines.append('    Tier 5: Generative Fallback (Always Works)')
new_func_lines.append('    """')
new_func_lines.append('    if not output_path:')
new_func_lines.append('        output_path = f"emotion_voice_outputs/emotion_{uuid.uuid4().hex[:8]}.mp3"')
new_func_lines.append('    os.makedirs("emotion_voice_outputs", exist_ok=True)')
new_func_lines.append('    safe_remove_file(output_path)')
new_func_lines.append('')
new_func_lines.append('    detected_language = st.session_state.get("emotion_voice_language", "English")')
new_func_lines.append('    use_hindi_voice = "Hindi" in detected_language or "Hinglish" in detected_language')
new_func_lines.append('')
new_func_lines.append('    # --- Emotion-to-SSML Style Mapping ---')
new_func_lines.append('    emotion_ssml_map = {')
new_func_lines.append('        "neutral": ("neutral", "general", 0),')
new_func_lines.append('        "happy": ("cheerful", "happy", 0.8),')
new_func_lines.append('        "sad": ("sad", "sad", 0.3),')
new_func_lines.append('        "angry": ("angry", "angry", 0.9),')
new_func_lines.append('        "excited": ("excited", "excited", 1.0),')
new_func_lines.append('        "serious": ("serious", "serious", 0.2),')
new_func_lines.append('        "mysterious": ("whispering", "newscast", 0.4),')
new_func_lines.append('    }')
new_func_lines.append('')
new_func_lines.append('    # --- Emotion Prompt Engineering ---')
new_func_lines.append('    emotion_prefixes = {')
new_func_lines.append('        "neutral": "",')
new_func_lines.append('        "happy": "[Speak with bright, cheerful enthusiasm and a smile in your voice] ",')
new_func_lines.append('        "sad": "[Speak with a soft, melancholic, and heart-touching tone] ",')
new_func_lines.append('        "angry": "[Speak with intense anger, frustration, and aggressive tone] ",')
new_func_lines.append('        "excited": "[Speak with high energy, excitement, and electrifying enthusiasm] ",')
new_func_lines.append('        "serious": "[Speak with deep, serious, professional, and commanding authority] ",')
new_func_lines.append('        "mysterious": "[Speak in a slow, hushed, intriguing, and enigmatic whisper] ",')
new_func_lines.append('    }')
new_func_lines.append('    emotion_prefix = emotion_prefixes.get(emotion, "")')
new_func_lines.append('    modified_text = emotion_prefix + text')
new_func_lines.append('')
new_func_lines.append('    # ========== TIER 1: ELEVENLABS (BEST QUALITY) ==========')
new_func_lines.append('    eleven_key = os.getenv("ELEVENLABS_API_KEY") or get_system_secret("ELEVENLABS_API_KEY")')
new_func_lines.append('    if eleven_key and elevenlabs_voice_id:')
new_func_lines.append('        try:')
new_func_lines.append('            stability = emotion_ssml_map.get(emotion, ("neutral", "general", 0.5))[2]')
new_func_lines.append('            similarity_boost = 0.75')
new_func_lines.append('')
new_func_lines.append('            url = f"https://api.elevenlabs.io/v1/text-to-speech/{elevenlabs_voice_id}"')
new_func_lines.append('            headers = {"Accept": "audio/mpeg", "Content-Type": "application/json", "xi-api-key": eleven_key}')
new_func_lines.append('')
new_func_lines.append('            payload = {')
new_func_lines.append('                "text": modified_text,')
new_func_lines.append('                "model_id": "eleven_multilingual_v2",')
new_func_lines.append('                "voice_settings": {')
new_func_lines.append('                    "stability": stability,')
new_func_lines.append('                    "similarity_boost": similarity_boost,')
new_func_lines.append('                    "style": 0.5 if emotion != "neutral" else 0.0,')
new_func_lines.append('                    "use_speaker_boost": True,')
new_func_lines.append('                }')
new_func_lines.append('            }')
new_func_lines.append('')
new_func_lines.append('            resp = requests.post(url, json=payload, headers=headers, timeout=30)')
new_func_lines.append('            if resp.status_code == 200 and len(resp.content) > 2000:')
new_func_lines.append('                with open(output_path, "wb") as f:')
new_func_lines.append('                    f.write(resp.content)')
new_func_lines.append('                if os.path.exists(output_path) and os.path.getsize(output_path) > 2000:')
new_func_lines.append('                    if is_audio_audible(output_path):')
new_func_lines.append('                        logger.info(f"ElevenLabs World-Class: {text[:40]}... [emotion={emotion}]")')
new_func_lines.append('                        return output_path')
new_func_lines.append('        except Exception as e:')
new_func_lines.append('            logger.warning(f"ElevenLabs failed: {e}")')
new_func_lines.append('')
new_func_lines.append('    # ========== TIER 2: AZURE TTS (PREMIUM) ==========')
new_func_lines.append('    azure_key = os.getenv("AZURE_SPEECH_KEY") or get_system_secret("AZURE_SPEECH_KEY")')
new_func_lines.append('    azure_region = os.getenv("AZURE_SPEECH_REGION") or get_system_secret("AZURE_SPEECH_REGION", "eastus")')
new_func_lines.append('    if azure_key and azure_region:')
new_func_lines.append('        try:')
new_func_lines.append('            if use_hindi_voice:')
new_func_lines.append('                voice_name = "hi-IN-MadhurNeural" if voice_type == "male" else "hi-IN-SwaraNeural"')
new_func_lines.append('            else:')
new_func_lines.append('                voice_name = "en-US-GuyNeural" if voice_type == "male" else "en-US-JennyNeural"')
new_func_lines.append('')
new_func_lines.append('            style = emotion_ssml_map.get(emotion, ("neutral", "general", 0.5))[0]')
new_func_lines.append('')
new_func_lines.append('            url = f"https://{azure_region}.tts.speech.microsoft.com/cognitiveservices/v1"')
new_func_lines.append('            headers = {')
new_func_lines.append('                "Ocp-Apim-Subscription-Key": azure_key,')
new_func_lines.append('                "Content-Type": "application/ssml+xml",')
new_func_lines.append('                "X-Microsoft-OutputFormat": "audio-24khz-96kbitrate-mono-mp3"')
new_func_lines.append('            }')
new_func_lines.append('')
new_func_lines.append('            # Build SSML safely')
new_func_lines.append('            if use_hindi_voice:')
new_func_lines.append('                ssml_parts = [')
new_func_lines.append('                    "<speak version=\\"1.0\\" xmlns=\\"http://www.w3.org/2001/10/synthesis\\" xml:lang=\\"hi-IN\\">",')
new_func_lines.append('                    f"<voice name=\\"{voice_name}\\">",')
new_func_lines.append('                    f"<prosody rate=\\"5%\\" pitch=\\"0%\\">{text}</prosody>",')
new_func_lines.append('                    "</voice>",')
new_func_lines.append('                    "</speak>"')
new_func_lines.append('                ]')
new_func_lines.append('            else:')
new_func_lines.append('                ssml_parts = [')
new_func_lines.append('                    "<speak version=\\"1.0\\" xmlns=\\"http://www.w3.org/2001/10/synthesis\\" xmlns:mstts=\\"https://www.w3.org/2001/mstts\\" xml:lang=\\"en-US\\">",')
new_func_lines.append('                    f"<voice name=\\"{voice_name}\\">",')
new_func_lines.append('                    f"<mstts:express-as style=\\"{style}\\" styledegree=\\"1.5\\">",')
new_func_lines.append('                    f"<prosody rate=\\"5%\\" pitch=\\"0%\\">{text}</prosody>",')
new_func_lines.append('                    "</mstts:express-as>",')
new_func_lines.append('                    "</voice>",')
new_func_lines.append('                    "</speak>"')
new_func_lines.append('                ]')
new_func_lines.append('            ssml = "".join(ssml_parts)')
new_func_lines.append('')
new_func_lines.append('            resp = requests.post(url, headers=headers, data=ssml, timeout=30)')
new_func_lines.append('            if resp.status_code == 200 and len(resp.content) > 1000:')
new_func_lines.append('                with open(output_path, "wb") as f:')
new_func_lines.append('                    f.write(resp.content)')
new_func_lines.append('                if os.path.exists(output_path) and is_audio_audible(output_path):')
new_func_lines.append('                    logger.info(f"Azure World-Class: {text[:40]}... [emotion={emotion}]")')
new_func_lines.append('                    return output_path')
new_func_lines.append('        except Exception as e:')
new_func_lines.append('            logger.warning(f"Azure TTS failed: {e}")')
new_func_lines.append('')
new_func_lines.append('    # ========== TIER 3: GOOGLE CLOUD TTS ==========')
new_func_lines.append('    google_key = os.getenv("GOOGLE_TTS_API_KEY") or get_system_secret("GOOGLE_TTS_API_KEY")')
new_func_lines.append('    if not google_key:')
new_func_lines.append('        google_key = os.getenv("GEMINI_API_KEY") or get_system_secret("GEMINI_API_KEY")')
new_func_lines.append('    if google_key:')
new_func_lines.append('        try:')
new_func_lines.append('            import base64')
new_func_lines.append('            ssml_gender = "MALE" if voice_type == "male" else "FEMALE"')
new_func_lines.append('            lang_code = "hi-IN" if use_hindi_voice else "en-US"')
new_func_lines.append('')
new_func_lines.append('            emotion_rates = {"neutral": 1.0, "happy": 1.1, "sad": 0.85, "angry": 1.15, "excited": 1.2, "serious": 0.9, "mysterious": 0.8}')
new_func_lines.append('            emotion_pitches = {"neutral": 0, "happy": 5, "sad": -3, "angry": 3, "excited": 6, "serious": -2, "mysterious": -4}')
new_func_lines.append('            speaking_rate = emotion_rates.get(emotion, 1.0)')
new_func_lines.append('            pitch = emotion_pitches.get(emotion, 0)')
new_func_lines.append('')
new_func_lines.append('            payload = {')
new_func_lines.append('                "input": {"text": text},')
new_func_lines.append('                "voice": {"languageCode": lang_code, "ssmlGender": ssml_gender},')
new_func_lines.append('                "audioConfig": {')
new_func_lines.append('                    "audioEncoding": "MP3",')
new_func_lines.append('                    "speakingRate": speaking_rate,')
new_func_lines.append('                    "pitch": pitch,')
new_func_lines.append('                    "volumeGainDb": 3.0,')
new_func_lines.append('                    "effectsProfileId": ["large-home-entertainment-class-device"]')
new_func_lines.append('                }')
new_func_lines.append('            }')
new_func_lines.append('')
new_func_lines.append('            resp = requests.post(')
new_func_lines.append('                f"https://texttospeech.googleapis.com/v1/text:synthesize?key={google_key}",')
new_func_lines.append('                json=payload, timeout=30')
new_func_lines.append('            )')
new_func_lines.append('            if resp.status_code == 200:')
new_func_lines.append('                audio_content = resp.json().get("audioContent")')
new_func_lines.append('                if audio_content:')
new_func_lines.append('                    with open(output_path, "wb") as f:')
new_func_lines.append('                        f.write(base64.b64decode(audio_content))')
new_func_lines.append('                    if os.path.exists(output_path) and os.path.getsize(output_path) > 2000:')
new_func_lines.append('                        logger.info(f"Google TTS World-Class: {text[:40]}... [emotion={emotion}]")')
new_func_lines.append('                        return output_path')
new_func_lines.append('        except Exception as e:')
new_func_lines.append('            logger.warning(f"Google TTS failed: {e}")')
new_func_lines.append('')
new_func_lines.append('    # ========== TIER 4: EDGE TTS (FREE, RELIABLE) ==========')
new_func_lines.append('    try:')
new_func_lines.append('        if edge_tts is not None:')
new_func_lines.append('            if use_hindi_voice:')
new_func_lines.append('                voice_candidates = [')
new_func_lines.append('                    "hi-IN-MadhurNeural" if voice_type == "male" else "hi-IN-SwaraNeural",')
new_func_lines.append('                    "en-IN-PrabhatNeural" if voice_type == "male" else "en-IN-NeerjaNeural",')
new_func_lines.append('                    "en-US-GuyNeural" if voice_type == "male" else "en-US-AriaNeural",')
new_func_lines.append('                ]')
new_func_lines.append('            else:')
new_func_lines.append('                voice_candidates = [')
new_func_lines.append('                    "en-US-GuyNeural" if voice_type == "male" else "en-US-AriaNeural",')
new_func_lines.append('                    "en-GB-RyanNeural" if voice_type == "male" else "en-GB-SoniaNeural",')
new_func_lines.append('                    "en-IN-PrabhatNeural" if voice_type == "male" else "en-IN-NeerjaNeural",')
new_func_lines.append('                ]')
new_func_lines.append('')
new_func_lines.append('            emotion_edge_styles = {')
new_func_lines.append('                "neutral": "general",')
new_func_lines.append('                "happy": "cheerful",')
new_func_lines.append('                "sad": "sad",')
new_func_lines.append('                "angry": "angry",')
new_func_lines.append('                "excited": "excited",')
new_func_lines.append('                "serious": "serious",')
new_func_lines.append('                "mysterious": "whispering",')
new_func_lines.append('            }')
new_func_lines.append('')
new_func_lines.append('            for voice_name in voice_candidates:')
new_func_lines.append('                try:')
new_func_lines.append('                    safe_remove_file(output_path)')
new_func_lines.append('                    edge_emotion = emotion_edge_styles.get(emotion, "general")')
new_func_lines.append('')
new_func_lines.append('                    async def _do_edge_tts():')
new_func_lines.append('                        communicate = edge_tts.Communicate(text, voice_name)')
new_func_lines.append('                        await communicate.save(output_path)')
new_func_lines.append('')
new_func_lines.append('                    run_async_in_thread(_do_edge_tts())')
new_func_lines.append('')
new_func_lines.append('                    if os.path.exists(output_path) and os.path.getsize(output_path) > 2048:')
new_func_lines.append('                        logger.info(f"Edge TTS World-Class: {text[:40]}... [emotion={emotion}]")')
new_func_lines.append('                        return output_path')
new_func_lines.append('                except Exception as voice_error:')
new_func_lines.append('                    logger.warning(f"Edge TTS voice failed ({voice_name}): {voice_error}")')
new_func_lines.append('                    continue')
new_func_lines.append('    except Exception as e:')
new_func_lines.append('        logger.warning(f"Edge TTS failed: {e}")')
new_func_lines.append('')
new_func_lines.append('    # ========== TIER 5: GENERATIVE FALLBACK ==========')
new_func_lines.append('    try:')
new_func_lines.append('        if not os.path.exists(output_path) or os.path.getsize(output_path) < 1000:')
new_func_lines.append('            logger.info(f"Fallback: Generating tone audio for {text[:30]}...")')
new_func_lines.append('')
new_func_lines.append('            import struct')
new_func_lines.append('            import math')
new_func_lines.append('')
new_func_lines.append('            sample_rate = 22050')
new_func_lines.append('            duration = max(2.0, len(text) * 0.08)')
new_func_lines.append('            num_samples = int(sample_rate * duration)')
new_func_lines.append('')
new_func_lines.append('            freq_map = {"neutral": 220, "happy": 440, "sad": 180, "angry": 330, "excited": 550, "serious": 150, "mysterious": 100}')
new_func_lines.append('            amp_map = {"neutral": 0.3, "happy": 0.4, "sad": 0.2, "angry": 0.5, "excited": 0.5, "serious": 0.25, "mysterious": 0.15}')
new_func_lines.append('            freq = freq_map.get(emotion, 220)')
new_func_lines.append('            amplitude = amp_map.get(emotion, 0.3)')
new_func_lines.append('')
new_func_lines.append('            samples = []')
new_func_lines.append('            for i in range(num_samples):')
new_func_lines.append('                t = i / sample_rate')
new_func_lines.append('                vibrato = math.sin(2 * math.pi * 5 * t) * 0.1 if emotion in ("happy", "excited", "sad") else 0')
new_func_lines.append('                value = amplitude * math.sin(2 * math.pi * freq * t + vibrato * 2 * math.pi)')
new_func_lines.append('                value += 0.3 * amplitude * math.sin(2 * math.pi * freq * 2 * t)')
new_func_lines.append('                value += 0.1 * amplitude * math.sin(2 * math.pi * freq * 3 * t)')
new_func_lines.append('                value = max(-1.0, min(1.0, value))')
new_func_lines.append('                samples.append(struct.pack("h", int(value * 32767)))')
new_func_lines.append('')
new_func_lines.append('            import wave')
new_func_lines.append('            with wave.open(output_path, "w") as wav_file:')
new_func_lines.append('                wav_file.setnchannels(1)')
new_func_lines.append('                wav_file.setsampwidth(2)')
new_func_lines.append('                wav_file.setframerate(sample_rate)')
new_func_lines.append('                wav_file.writeframes(b"".join(samples))')
new_func_lines.append('')
new_func_lines.append('            mp3_path = output_path.replace(".mp3", "_temp.mp3")')
new_func_lines.append('            cmd = ["ffmpeg", "-y", "-i", output_path, "-codec:a", "libmp3lame", "-qscale:a", "2", mp3_path]')
new_func_lines.append('            try:')
new_func_lines.append('                subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)')
new_func_lines.append('                if os.path.exists(mp3_path) and os.path.getsize(mp3_path) > 1000:')
new_func_lines.append('                    safe_remove_file(output_path)')
new_func_lines.append('                    shutil.move(mp3_path, output_path)')
new_func_lines.append('            except Exception:')
new_func_lines.append('                safe_remove_file(mp3_path)')
new_func_lines.append('')
new_func_lines.append('            if os.path.exists(output_path) and os.path.getsize(output_path) > 1000:')
new_func_lines.append('                logger.info(f"Generative Fallback success: {text[:30]}... [emotion={emotion}]")')
new_func_lines.append('                return output_path')
new_func_lines.append('')
new_func_lines.append('    except Exception as e:')
new_func_lines.append('        logger.error(f"All TTS tiers failed: {e}")')
new_func_lines.append('')
new_func_lines.append('    safe_remove_file(output_path)')
new_func_lines.append('    return None')

new_func = '\n'.join(new_func_lines)

new_content = content[:func_start] + new_func + content[func_end:]
with open('app.py', 'w', encoding='utf-8') as f:
    f.write(new_content)
print(f'Replaced generate_emotion_voice! New size: {len(new_func)} chars')
