GLOBAL_PLANS = {
    "subscriptions": {
        "free": {
            "name": "Free",
            "price": 0,
            "tokens": 0,
            "amount_paise": 0,
            "emoji": "🆓",
            "features": ["10 Free Tokens Monthly", "Watermark", "Basic AI Features"],
            "type": "monthly",
            "badge": "",
            "color": "#64748b",
            "description": "Free plan with limited features",
        },
        "standard": {
            "name": "Standard",
            "price": 99,
            "tokens": 90 + 10,
            "amount_paise": 9900,
            "emoji": "🥇",
            "features": ["70 Tokens Monthly", "No Watermark", "All AI Features"],
            "type": "monthly",
            "badge": "POPULAR",
            "color": "#f59e0b",
            "description": "Best value plan",
        },
        "cinematic": {
            "name": "Cinematic",
            "price": 299,
            "tokens": 250 + 50,
            "amount_paise": 29900,
            "emoji": "🥈",
            "features": ["230 Tokens Monthly", "No Watermark", "All AI Features"],
            "type": "monthly",
            "badge": "",
            "color": "#8b5cf6",
            "description": "For serious creators",
        },
        "premium": {
            "name": "Premium",
            "price": 499,
            "tokens": 410 + 90,
            "amount_paise": 49999,
            "emoji": "💎",
            "features": ["400 Tokens Monthly", "No Watermark", "All AI Features"],
            "type": "monthly",
            "badge": "",
            "color": "#ec4899",
            "description": "Professional creators",
        },
        "pro": {
            "name": "Pro",
            "price": 999,
            "tokens": 780 + 220,
            "amount_paise": 99900,
            "emoji": "👑",
            "features": ["850 Tokens Monthly", "No Watermark", "All AI Features"],
            "type": "monthly",
            "badge": "⭐ BEST VALUE",
            "color": "#f43f5e",
            "description": "Unlimited potential",
        },
        "enterprise": {
            "name": "Enterprise",
            "price": 1999,
            "tokens": 1500 + 500,
            "amount_paise": 199900,
            "emoji": "🏢",
            "features": [
                "1750 Tokens Monthly",
                "No Watermark",
                "All AI Features",
                "Priority Support",
                "Custom AI Models",
            ],
            "type": "monthly",
            "badge": "⭐ ENTERPRISE",
            "color": "#8b5cf6",
            "description": "Complete business solution",
        },
    },
    "one_time": {
        "topup_99": {
            "name": "Token Top-up",
            "price": 99,
            "tokens": 100,
            "amount_paise": 9900,
            "emoji": "🎯",
            "type": "prepaid",
            "badge": "💫 ONE-TIME",
            "color": "#45f3ff",
            "description": "One-time token purchase",
        },
        "topup_299": {
            "name": "Token Top-up",
            "price": 299,
            "tokens": 300,
            "amount_paise": 29900,
            "emoji": "🎯",
            "type": "prepaid",
            "badge": "💫 ONE-TIME",
            "color": "#45f3ff",
            "description": "One-time token purchase",
        },
        "topup_499": {
            "name": "Token Top-up",
            "price": 499,
            "tokens": 500,
            "amount_paise": 49900,
            "emoji": "🎯",
            "type": "prepaid",
            "badge": "💫 ONE-TIME",
            "color": "#45f3ff",
            "description": "One-time token purchase",
        },
        "topup_999": {
            "name": "Token Top-up",
            "price": 999,
            "tokens": 1000,
            "amount_paise": 99900,
            "emoji": "🎯",
            "type": "prepaid",
            "badge": "💫 ONE-TIME",
            "color": "#45f3ff",
            "description": "One-time token purchase",
        },
        "topup_1999": {
            "name": "Token Top-up",
            "price": 1999,
            "tokens": 2000,
            "amount_paise": 199900,
            "emoji": "🎯",
            "type": "prepaid",
            "badge": "💫 ONE-TIME",
            "color": "#45f3ff",
            "description": "One-time token purchase",
        },
    },
}
