[theme]
base = "dark"
primaryColor = "#d5db79fb"
backgroundColor = "#1a0715fd"
secondaryBackgroundColor = "#0a0305"
textColor = "#faf7f7"
font = "sans serif"

[server]
enableStaticServing = true
headless = true