[theme]
base = "dark"
primaryColor = "#8c44c8"
backgroundColor = "#10041a"
secondaryBackgroundColor = "#0a0c0b"
textColor = "#F1F5F9"
font = "sans serif"

[server]
enableStaticServing = true
headless = true