[theme]
base = "light"
primaryColor = "#13aa9e"
backgroundColor = "#f7f9f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#202b2c"
borderColor = "#dce5e2"
font = "sans serif"

[server]
enableStaticServing = true
headless = true