# Streamlit secrets - add your API keys here
# RAZORPAY_KEY_ID = ""
# RAZORPAY_KEY_SECRET = ""
# PIXABAY_API_KEY = ""
# PEXELS_API_KEY = ""
# STABILITY_API_KEY = ""
# REPLICATE_API_TOKEN = ""
# ELEVENLABS_API_KEY =
# DEEPINFRA_API_KEY = "paste_your_deepinfra_api_key_here"
# DEEPINFRA_API_TOKEN = ""